### ISSUE TITLE
Probably bug with group() scope in UsersTrait

### ISSUE THREAD

**Issue by justasLab** [mateusjunges/laravel-acl#133]
I want to get users who belong to admin group. I use this method:
$users = User::group('admin')->get();

Unfortunately this method returns a list of all users. So here's the bug or am I doing something wrong?

**Comment by mateusjunges** [comment]
@justasLab I fixed the bug and will tag a new release tomorrow by morning. Thanks for your report.

**Comment by mateusjunges** [comment]
@justasLab I fixed the bug with the [2.1.1](https://github.com/mateusjunges/laravel-acl/tree/2.1.1) release. Thanks for your report.

**Comment by TheTankFrank** [comment]
Laravel Says:
Trait "App\Models\UserTrait" not found
