### ISSUE TITLE
Add ignition solutions to Laravel ACL exceptions

### ISSUE THREAD

**Issue by mateusjunges** [mateusjunges/laravel-acl#137]
This is the documentation about [custom solutions][1] with ignition.

[1]: https://flareapp.io/docs/solutions/adding-custom-solutions

**Comment by ReeceM** [comment]
I would be happy to work on this. ?

**Comment by mateusjunges** [comment]
You are welcome!

**Comment by mateusjunges** [comment]
Fixed with #141
