### ISSUE TITLE
Error on Install Migrations

### ISSUE THREAD

**Issue by soyjonathanespinosa** [mateusjunges/laravel-acl#14]
Hi, I was trying to install your package, but I have an error and your migration and config publish don't work:

![error_laravel-acl](https://user-images.githubusercontent.com/18094435/56776704-5e369680-6793-11e9-80ab-8b015971bec2.png)

Migrating: 2019_03_16_005237_create_permissions_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `slug` varchar(255) not null, `description` text not null, `deleted_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at C:\-----
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''")
      C:\-----

  2   PDO::prepare("create table `` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `slug` varchar(255) not null, `description` text not null, `deleted_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'")
      C:\-----

  Please use the argument -v to see more details.

C:\------
λ php artisan vendor:publish --provider="Junges\ACL\ACLServiceProvider::class" --tag="config"
Publishing complete.

C:\-------
λ php artisan vendor:publish --provider="Junges\ACL\ACLServiceProvider::class" --tag="config"
Publishing complete.

I hope you can help because I want to use your package.

Thank you

**Comment by mateusjunges** [comment]
Which version are you trying to use?

**Comment by soyjonathanespinosa** [comment]
Package operations: 1 install, 0 updates, 0 removals
  - Installing mateusjunges/laravel-acl (1.0.3): Loading from cache

**Comment by soyjonathanespinosa** [comment]
I had to put manually the config file, then clear config cache, now I have:

Migrating: 2019_03_16_005538_create_user_has_permissions_table

   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `user_has_permissions` add constraint `user_has_permissions_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)

I'll try to fix it and let you know.

**Comment by soyjonathanespinosa** [comment]
Fixed and now working.

1.- Migrations are not working due config('acl.tables') at first installation, so is not getting config file in your package, then, config publish not working, so I had to copy acl.php to config and then clear cache and fixed.

2. Second error about creating foreing keys are due bigInteger user_id field, I already changed to integer and fixed.

Let me know your comments.

**Comment by soyjonathanespinosa** [comment]
Another Problem:

php artisan group:create Super Admin super-admin Super Administrador
  Too many arguments, expected arguments "command" "name" "slug" "description".

**Comment by mateusjunges** [comment]
The first problem is being fixed right now. About the second one, try using quotes in the arguments. This should work:

php artisan group: create "Super Admin" "super-admin" "Super Administrator"

**Comment by mateusjunges** [comment]
The problem was fixed in version 1.1.0. Thank you for your report. Make sure your users table is using bigIncrements / bigInteger as the primary key. Now the publishes should work correctly.

**Comment by soyjonathanespinosa** [comment]
Thank you

**Comment by mateusjunges** [comment]
Sorry, about the command, i miss a space between the group and create:
`php artisan group: create "Super Admin" "super-admin" "Super Administrator"`
The correct command is:
`php artisan group:create "Super Admin" "super-admin" "Super Administrator"`
