### ISSUE TITLE
Move facade/ignition to composer require

### ISSUE THREAD

**Issue by ReeceM** [mateusjunges/laravel-acl#146]
Hi Mateus, 

With regards the latest addition of the ignition solutions (#141) to the package and the addition of the `facade/ignition` package (#144) to make the ignition contracts work because they are bound to the container in the actual ignition package, I initially added it to the require-dev section of `laravel-acl`'s composer file as it functioned locally, 'it worked for me' situation .... 😄 

In hindsight and in light of #143, the latest comment by the @ACvijic there after it was closed, I figure that it should be added to the main `require` section of the composer file.

_I didn't do that originally as that seemed maybe a bit rude to force that need upon a person as it would suddenly result in them having a completely different error page than what they had unexpectedly._

This may be a bit confusing to a new person starting, or irritation to developers who might not have wanted ignition installed.

Could there be a discussion of how that could be solved?

I am thinking of the following options:
- Move the `facade/ignition` requirement to the `require` part of the composer file.
    - make a note about it installing this in the documents, then people know.
- or, add a suggests section of the composer file for the `facade/ignition` package, encouraging them to install it, but this would still result in a failure on first install (may not work/ give best install experience)
- or, make the ignition solutions an opt-in thing via the config file, and suggest the use of the `facade/ignition` package
   - this would fix the fact of 'suggesting' the use of ignition.

I thought this would be better to check here instead of opening another PR to just change the composer file again. It may be practical to make this more useful and functional.

**Comment by mateusjunges** [comment]
I think the best solution is to make the ignition solutions an opt-in using the config file. You are welcome to open a PR fixing it. Thanks!

**Comment by ReeceM** [comment]
@mateusjunges, okay I will have a look at it, it may not be immediately that i make a PR though, if thats alright?

--- 
If its made an opt-in, would you prefer then the `facade/ignition` requirement stays then as a dev on and it suggest the requirement on install via composer and also the artisan command?

**Comment by mateusjunges** [comment]
Yeah that's ok.
I think if we made it opt-in, the ignition can stay as a dev requirement, and install using artisan/composer.
