### ISSUE TITLE
can't sync group from user

### ISSUE THREAD

**Issue by mosi3883** [mateusjunges/laravel-acl#155]
the **UsersTrait** needs have **syncGroup** method
i know i can use some thing like
```
$user->groups()->sync($request->groups);
```

but code has **syncPermissions** so i think u should add this one too

**Comment by mateusjunges** [comment]
Hi @mosi3883, first of all, thanks for your suggestion. I'll consider implementing this after the hollidays.
Thank you!

**Comment by mateusjunges** [comment]
@mosi3883 added in #157

**Comment by mateusjunges** [comment]
Forgot to mention, but you can upgrade to version 2.3.0 to use this new feature.
