### ISSUE TITLE
Uma tabela a mais para atribuir setores

### ISSUE THREAD

**Issue by Luizgpp** [mateusjunges/laravel-acl#178]
Ola Mateus tudo bem? Obrigado pelo seu conhecimento e fornece-lo pra todos!

Gostaria de tirar uma duvida e talvez essa dúvida pode surgir uma nova funcionalidade no ACL.

Tenho uma necessidade de criar uma tabela de setores (setores de uma empresa, RH, Diretoria, Marketing, etc) e em cada setor os usuários teriam "Roles" e "Permissions".
EX: 
João - Diretoria -Admin - todas as permissões

Mas ele também pode fazer parte de outro setor.

João - Marketing - supervisor - permissões de supervisor de marketing.

Não sei se deu pra entender, mas a ideia seria de adicionar regras e permissões para um setor, onde usuário podem fazer parte de mais de um setor.

Não sei se consegui ser claro, mas como conseguiria fazer isso utilizando o ACL?

Obrigado desde já!!

**Comment by mateusjunges** [comment]
Olá @Luizgpp 
No momento, o pacote não possui a funcionalidade de gerenciar as permissões de multiplos models, que seria o caso aqui. Você precisa armazenar tanto permissões para usuários e grupos quanto para setores. Assim, o usuário que pertence a um setor com permissão X tem acesso a áreas do sistema que dependem dessa permissão. Você precisa implementar esta lógica manualmente em seu sistema. Você vai precisar de uma tabela `sectors`, para armazenar os setores,  `sector_has_permissions`, para armazenar as permissões dos setores, `sector_has_groups`, para armazenar os grupos aos quais cada setor pertencem, além de uma tabela para armazenar os setores aos quais os usuários pertencem, que vou chamar de `user_has_sectors`.
Assim, você pode sobrescrever os métodos que são disponibilizados por este pacote no seu sistema, para que a lógica de controle de acesso funcione verificando também as permissões dos setores, e não apenas as permissões de grupos e as atribuidas diretamente aos usuários.

Se não estou enganado, você vai precisar alterar o método `hasPermission`, na `UsersTrait`, e `ACLServiceProvider`, pra que as gates os método de verificação de permissões funcionem junto com os setores.

**Comment by Luizgpp** [comment]
Nossa, obrigado pela ajuda. Não é tão simples como pensei. Irei ver como posso resolver isso.

Obridago!!
