### ISSUE TITLE
There is no permission with this slug

### ISSUE THREAD

**Issue by ITDeveloperDotUz** [mateusjunges/laravel-acl#197]
**I am getting an error when assigning  a permission to my user**

My UserController.php file:
```
        $user = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
        ]);
        if ($data['permission']) {
            $permissions = [];
            foreach ($data['permission'] as $key => $value) {
                $permissions[] = $key;
            }
            $user->assignPermissions($permissions);
        }
        if ($data['group']) {
            $user->assignGroup($data['group']);
        }
```

a permiision with that slug exists in db in permissions table, But it shows an exception:
**There is no permission with this slug: 'c-order'**
I didn't change anything in config files

**Comment by mateusjunges** [comment]
Good morning, 
Which laravel, php and laravel-acl version are you using?

**Comment by ITDeveloperDotUz** [comment]
I'm using:
php: 7.3.20
laravel: 7.0
laravel-acl: 2.3

**Comment by mateusjunges** [comment]
Laravel ACL only added support for laravel v7.x on version [2.4.0](https://github.com/mateusjunges/laravel-acl/tree/2.4.0) and higher.

The version 2.3 of this package are tested only with laravel v5.6, v5.7, v5.8 and v6.x.
Can you try to upgrade your laravel-acl dependency?

**Comment by ITDeveloperDotUz** [comment]
Hi!
I upgraded laravel-acl to 2.5 and getting the same error

**Comment by ITDeveloperDotUz** [comment]
I solved this issue!
in my view I changed input name
From:
```
<label>
     <input type="checkbox" name="permission['{{ $pValue[$value] }}']" />
     <span></span>
</label>
```

To
```
<label>
     <input type="checkbox" name="permission[{{ $pValue[$value] }}]" />
     <span></span>
</label>
```

Simply I removed the single quotes. So in my controller I didn't change anything.
it caused an error because It took a slug including single quotes
`"'c-order'"`
And now after removing it works.

**Comment by mateusjunges** [comment]
Glad you solved it 😃
