### ISSUE TITLE
The `can` directive does not work

### ISSUE THREAD

**Issue by metif12** [mateusjunges/laravel-acl#210]
blade diractive @can and auth()->user()->can($permission) not work!
@permission is good

**Comment by mateusjunges** [comment]
Hi @metif12, can you add your code to the issue?

**Comment by metif12** [comment]
Hi,
i was using the package like this:
Route::view('/', 'nAdmin.holes')
->middleware('permissions:admin-view-holes')
->name('holes');
and @can directive in the layouts.
i does all setup in the manual. it was working but we received an issue about permissions are not working.
when i check it in tinker i found every things are ok but just result of can as function of User model is wrong.
![image](https://user-images.githubusercontent.com/26581685/116609908-2c400800-a94a-11eb-9663-85788e629bf2.png)

**Comment by metif12** [comment]
hi, i guess it was because of overwite isAdmin function in user Model

**Comment by mateusjunges** [comment]
Can you add the `isAdmin` function you have in your model?

**Comment by metif12** [comment]
we have multipanel structure and admin is a model. so we define a isAdmin function in user model to determine if a user is admin or not. i sugest to rename isAdmin to isSuperAdmin at UsersTrait. that is more specific and less possible to overwrite.

**Comment by mateusjunges** [comment]
@metif12 i think it's better to rename your `isAdmin` function. If i rename the function in this package i'll need to tag a new major version because it introduces breaking changes. You can do it easily in your project using IDE helpers.
