### ISSUE TITLE
Error when checking permission for user without direct permission but has group permissions.

### ISSUE THREAD

**Issue by gnguyo** [mateusjunges/laravel-acl#221]
**Describe the bug**
Library throws error when checking user permission that does not have any permission but is assigned to a group with a permission.
Error: Call to a member function where() on null
File: mateusjunges\laravel-acl\src\Traits\UsersTrait.php:76

**To Reproduce**
1. Ensure user has no direct permission assigned.
2. Create new group
3. Create new permission
4. Assign permission to group.
5. Assign user to group.
6. Check if user has permission. ( $user->hasPermission('view-students') )

**Expected behavior**
User should have permission because they are in a group with that permission.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 91.0.4472.106 (Official Build) (64-bit)

**Additional context**
None.

**Comment by mateusjunges** [comment]
Hi @gnguyo, which version of Laravel  and laravel-acl are you using? The tests for this case are passing and i followed your steps to reproduce the bug, but it's working fine for me.

```php
Route::get('/', function () {
    $user = \App\Models\User::first();

    $directPermissions = $user->permissions;

    $group = \Junges\ACL\Http\Models\Group::first();

    $group->assignPermissions(1);

    $user->assignGroup(1);

    return response()->json([
        'has_permission' => $user->hasPermission('test-permission'),
        'direct_permissions' => $directPermissions
    ]);
});
```

This is the result:

```json
{
    "has_permission": true,
    "direct_permissions": []
}
```

**Comment by gnguyo** [comment]
Apologies, seems it was a custom library i was using which was initializing the permission attribute as null.

**Comment by mateusjunges** [comment]
@gnguyo thanks for the update.
