### ISSUE TITLE
support laravel 9 with php8.1

### ISSUE THREAD

**Issue by metif12** [mateusjunges/laravel-acl#248]
this package is not compatible with laravel 9 and php8.1. error whe trying to install:
  Problem 1
    - Root composer.json requires mateusjunges/laravel-acl ^3.0 -> satisfiable by mateusjunges/laravel-acl[3.0.0, 3.0.1, 3.x-dev].
    - mateusjunges/laravel-acl[3.0.0, ..., 3.x-dev] require illuminate/auth ^7.28|^8.0 -> found illuminate/auth[v7.28.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require mateusjunges/laravel-acl:*" to figure out if any version is installable, or "composer require mateusjunges/laravel-acl:^2.1" if you know which you need.

**Comment by metif12** [comment]
thank you.

**Comment by mateusjunges** [comment]
@metif12 laravel 9 support released on v3.0.2
