### ISSUE TITLE
UsersTrait not exist

### ISSUE THREAD

**Issue by TheTankFrank** [mateusjunges/laravel-acl#253]
I will use ACL. Installing is not the Problem.

When i add usersTrait. Laravel Says:
Trait "App\Models\UserTrait" not found.

I have reinstall but i get the error again.

not Exist
use Junges\ACL\Concerns\UsersTrait;

I use Laravel Version is 9.5.1 .

And when i use 

php artisan permission:create

Shell ask:

slug not esist in table.

**Comment by TheTankFrank** [comment]
My Laravel Version is 9.5.1 .

**Comment by TheTankFrank** [comment]
OK, Version 4 not work for me. I use Version 3.0.2 and it work

**Comment by mateusjunges** [comment]
Hi @TheTankFrank, i'll take a look and fix this command in v4. Thanks for reporting.
