### ISSUE TITLE
Cannot assign null to property Junges\ACL\AclRegistrar::$cacheKey of type string

### ISSUE THREAD

**Issue by markplus** [mateusjunges/laravel-acl#259]
I have updated from Laravel 8 to Laravel 9 but now I get an error that I can't find solutions on the net, I don't know what to do

Error
PHP 8.1.6
9.32.0
Cannot assign null to property Junges\ACL\AclRegistrar::$cacheKey of type string

**Comment by quindo** [comment]
> I have updated from Laravel 8 to Laravel 9 but now I get an error that I can't find solutions on the net, I don't know what to do
> 
> Error PHP 8.1.6 9.32.0 Cannot assign null to property Junges\ACL\AclRegistrar::$cacheKey of type string

Pretty sure you are running into this issue because you did not delete the old config/acl.php file.

**Comment by mateusjunges** [comment]
I'm no longer maintaining this package. Please, use `spatie/laravel-permission`
