### ISSUE TITLE
acl:reset-cache command is not registered

### ISSUE THREAD

**Issue by Lumrenion** [mateusjunges/laravel-acl#264]
**Describe the bug**
In laravel-acl 4.2.2, the command acl:reset-cache is not registered in ServiceProvider.

**To Reproduce**
1. call `php artisan acl:reset-cache` as in documentation
2. See the error message `Command "acl:reset-cache" is not defined.`

**Expected behavior**
The command get's called.

**Comment by mateusjunges** [comment]
I'm no longer maintaining this package. Please, use `spatie/laravel-permission`
