### ISSUE TITLE
The groups' name on the select need "[]"

### ISSUE THREAD

**Issue by wilo-ahadi** [mateusjunges/laravel-acl#54]
The groups'name need double quote "groups[]" : https://github.com/mateusjunges/laravel-acl/blob/2357c686a3d9f416691fcec7088a91a453792c4e/src/resources/views/_forms/users/add-group.blade.php#L30 ... thanks for this tool

**Comment by mateusjunges** [comment]
Sorry about that. I'll fix it as soon as possible.Thanks for your report.

**Comment by mateusjunges** [comment]
## Issue has been fixed on version [1.4.2](https://github.com/mateusjunges/laravel-acl/tree/1.4.2)
If you find any other problem, please feel free to report then.
