### ISSUE TITLE
$permissions aren't selected in _forms/groups/group.blade.php

### ISSUE THREAD

**Issue by wilo-ahadi** [mateusjunges/laravel-acl#56]
the $model must be "config('acl.models.permission')" : https://github.com/mateusjunges/laravel-acl/blob/a855879540dfc38f0b8a76c3bb74d172526a46f3/src/Traits/GroupsTrait.php#L28 ... it's why the $group's $permissions aren't selected in the form : https://github.com/mateusjunges/laravel-acl/blob/a855879540dfc38f0b8a76c3bb74d172526a46f3/src/resources/views/_forms/groups/group.blade.php#L50

**Comment by mateusjunges** [comment]
Fixed on [1.4.3](https://github.com/mateusjunges/laravel-acl/tree/1.4.3)
