### ISSUE TITLE
seeder programatically

### ISSUE THREAD

**Issue by elmakong** [mateusjunges/laravel-acl#68]
1st, i tried to use artisan command with phpstorm, but the command seems to be not registered(no autocomplete).
2nd, when trying to call artisan command [programmatically,](https://laravel.com/docs/5.8/artisan#programmatically-executing-commands) it cant bypass the confirm function inside the CreateGroup.php(console\commands). 
also, there is Portuguese language in that confirmation prompt, maybe use English so its easier to understand? PS: i use google translate to understand that prompt message.

the point is, i want to be able to seed my permission database such as admin permissions and regular member/user permissions with different group without the need to manually issuing command to artisan for each and every one of the group or permission.

Laravel v5.8.16
ACL v1.6.0

**Comment by mateusjunges** [comment]
I think you can create a seeder for your application using the `php artisan make:seed SomAwesomeName`
and defining you permissions and groups there. Then, you can use the `assignPermissions(['permission-slug'])` function to assing permissions for you system users or groups. 

For example:

```php
use Illuminate\Database\Seeder;
use App\User;
use Junges\ACL\Http\Models\Group;

class PermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create some permissions:
        DB::table('permissions')->insert([
            ['name' => 'admin', 'slug' => 'admin', 'description' => 'This is the admin permission'],
            ['name' => 'another permission', 'slug'=>'another-permission', 'description' => 'this is another permission'],
        ]);
        // Create some groups:
        Group::create([
            'name' => 'Group one',
            'slug' => 'group-1',
            'description' => 'This is the group one',
        ]);
       //Then, you can add permissions to groups and add the user to any group you want:
        $group = Group::find(1);
        $group->assignPermissions(['admin']);
        
        $user = User::find(1);
        $user->assignGroup(['group-1']);
        //Now the user has the permissions above, because he is associated with one group that has the permissions.
        //Otherwise, you can add the permissions direct to the user, without need to associate the permissions with one group:
        $user->assignPermissions(['admin', 'another-permission']);
    }
}
```

**Comment by mateusjunges** [comment]
About the portuguese language, i'll change to english.

**Comment by mateusjunges** [comment]
About use the commands programatically, the commands were created to be used through the CLI, not programmatically, since you can use database seeds to create the permissions in your database.

**Comment by mateusjunges** [comment]
I changed the commands that were in Portuguese and changed it to English. I hope it helps.
These changes are in the version [1.6.1](https://github.com/mateusjunges/laravel-acl/tree/1.6.1). Here is the [changelog](https://github.com/mateusjunges/laravel-acl/blob/master/CHANGELOG.md).

**Comment by elmakong** [comment]
Would it be possible without directly calling illuminatedb
`DB::table('permissions')->insert();`

so it can be shorthanded just like the artisan command?
Maybe like this:
`Acl::createPerm('name','slug','optional-desc');`
`Acl::createGroup(name','slug','optional-desc');`

**Comment by mateusjunges** [comment]
Yes, you can use the `permission` and `group` model:

```php
//For permissions:
Permission::create([
    'name' => 'permission one',
    'slug' => 'permission-one',
    'description' => 'this is the permission one'
]);

//For groups:
Group::create([
    'name' => 'group one''
    'slug' => 'group-1',
    'description' => 'This is the group one'
]):
```
