### ISSUE TITLE
Error in $user->syncPermissions

### ISSUE THREAD

**Issue by soyjonathanespinosa** [mateusjunges/laravel-acl#73]
I am testing the $user->syncPermissions(); but when you not send any permission (Null) it giving me:

Argument 1 passed to App\User::syncPermissions() must be of the type array, null given, called in 

The problem is this function:

public function syncPermissions(array $permissions)
    {
        $permissions = $this->convertToPermissionIds($permissions);
        if ($permissions->count() == 0)
            return false;
        $this->permissions()->sync($permissions);
        return $this;
 
    }

So I suggest to add null parameter.

**Comment by mateusjunges** [comment]
I think you are trying to remove all user permissions. Am i right?

**Comment by soyjonathanespinosa** [comment]
Yes I am testing removing all permissions, I have 1.1.

**Comment by soyjonathanespinosa** [comment]
Another question, how can I sync groups to a user?. like syncPermissions?

**Comment by mateusjunges** [comment]
In this version you should use `revokePermissions()` to remove user permissions. It can accept an array of permissions, as documented on [README.md](https://github.com/mateusjunges/laravel-acl/tree/1.1.1#1---revoke-permissions-from-user) file.  The `syncGroups()` method will be implemented in next package release. I think you can upgrade to `1.7.0` which has `revokeAllPermissions` method, that shoud solve your problem for now.

**Comment by soyjonathanespinosa** [comment]
Ok will update. Thank you
