### ISSUE TITLE
Customize Migration Problem

### ISSUE THREAD

**Issue by TuplesDev** [mateusjunges/laravel-acl#75]
**Describe the bug**
Customized migration table doesn't get reflected when running _php artisan migrate_.
Migration process will use migration defined in _[root]/vendor/mateusjunges/laravel-acl/src/database/migrations/***.php_ and not from _[root]/database/migrations/vendor/junges/acl/***.php_.

**To Reproduce**
Test using version 1.7.1
1. Run command _php artisan vendor:publish --provider="Junges\ACL\ACLServiceProvider" --tag="migrations"_
2. Edit and add a new column _$table->uuid('uuid')_ in _[root]/database/migrations/vendor/junges/acl/create_permissions_table.php_
3. Run command _php artisan migrate_
4. Check database for changes

**Comment by mateusjunges** [comment]
I have added a way to customize you tables in the last release, [1.7.2](https://github.com/mateusjunges/laravel-acl/tree/1.7.2)

You can update you package version, and add the `custom_migrations => true` to the `config/acl.php` file. With this new config, laravel will look for migrations inside the `database/migrations/vendor/junges/acl/` folder, where you can customize the files that you need.

See [installation](https://github.com/mateusjunges/laravel-acl/tree/1.7.2#installation)

I'm sorry about that, i think i dont have tested change the migrations after publish then. 

Thanks for report that.

**Comment by mateusjunges** [comment]
Did this solve your problem?

**Comment by TuplesDev** [comment]
Yes, thats solved it. Thanks..
